### ISSUE TITLE
회원가입 시 약관

### ISSUE THREAD

**Issue by birdieHyun** [Upbrella/Upbrella_front#211]
## 📌 Feature
<img width="478" alt="스크린샷 2023-10-11 오후 4 43 08" src="https://user-images.githubusercontent.com/115435784/274182037-72a2605b-e32f-4325-a442-6b61ceff65ff.png">

회원가입을 위해 이름, 전화번호를 입력 후 약관을 읽기 위해 진입한 후 뒤로가기를 할 경우 기존에 입력한 정보가 사라집니다. 
원활한 회원 가입 플로우를 위해서는 약관을 새창에서 읽을 수 있도록 하거나, 데이터를 보존할 수 있도록 하는게 좋을 것 같은데 어떻게 생각하시나요? 

## 📜 To Do

- [ ]

**Comment by ShinChanU** [comment]
약관을 새창에서 읽을 수 있도록 수정하는게 좋을 것 같네요 감사합니다 ~!
