### ISSUE TITLE
계좌 정보 등록 / 변경

### ISSUE THREAD

**Issue by birdieHyun** [Upbrella/Upbrella_front#212]
## 📌 Feature

<img width="902" alt="스크린샷 2023-10-11 오후 5 06 57" src="https://user-images.githubusercontent.com/115435784/274191867-1377fc81-bbf8-418a-83e6-5b361add90d8.png">

회원가입 및 회원가입 후 계좌번호를 입력할 때 숫자 외에도 입력이 되는 중입니다. 
백엔드에서도 예외처리할 계획인데 프론트에서도 같이 해주시면 감사하겠습니다!

## 📜 To Do

- [ ]

**Comment by ShinChanU** [comment]
감사합니다 ~ ! 숫자만 입력되도록 수정하겠습니다 ~!
