### ISSUE TITLE
[FIX] 협업지점 등록 안되어있는 경우 화면 렌더링 안되는 이슈

### ISSUE THREAD

**Issue by Gwonwoo-Nam** [Upbrella/Upbrella_front#266]
프로덕션 서버에 기존 개발 DB -> 프로덕션 DB로 변경했습니다.
지금 데이터가 없는데, 아래처럼 데이터가 없을 때 화면이 렌더링이 안되는 문제가 있습니다.

![스크린샷 2023-12-14 오후 10 43 20](https://github.com/UPbrella/UPbrella_front/assets/115435784/9a8ae682-bcee-4e8c-b0db-75febfbeb662)

**Comment by ShinChanU** [comment]
해결 완료 했습니다 ~!
