### ISSUE TITLE
[FIX] 회원 가입 시 '회원정보를 가져오지 못했습니다' 에러 토스트 발생

### ISSUE THREAD

**Issue by Gwonwoo-Nam** [Upbrella/Upbrella_front#267]
## 이슈
회원 가입 성공 시 '회원 정보를 가져오지 못했습니다' 토스트가 성공 토스트와 함께 보이는 문제가 있습니다.

## 이미지
![스크린샷 2023-12-14 오후 10 43 35](https://github.com/UPbrella/UPbrella_front/assets/115435784/7f4ea496-4e18-4c3b-be7e-a8dde7205e49)

**Comment by ShinChanU** [comment]
해결 완료 했습니다 ~!
