### ISSUE TITLE
API 변경에 따른 수정 요청 

### ISSUE THREAD

**Issue by birdieHyun** [Upbrella/Upbrella_front#284]
## 📌 Feature

<img width="966" alt="스크린샷 2023-12-19 오전 9 55 06" src="https://github.com/UPbrella/UPbrella_front/assets/115435784/d7e51555-8a85-45e3-a935-dd8583eae41c">
업브렐라 프로젝트 시작 당시 비밀번호 필드를 추가했었는데 현재는 사용하지 않는 필드라서 삭제 요청드립니다. <br>
현재 비밀번호는 지정해서 사용하는 것이 아닌, 보관함의 secret Key를 가지고 랜덤하게 생성됩니다!

## 📜 To Do

- [ ]

**Comment by ShinChanU** [comment]
이 부분도 수정 후 배포했습니다 ~!

@birdieHyun

**Comment by birdieHyun** [comment]
확인했습니다 감사합니다!
