### ISSUE TITLE
[Bug] 우산 관리 페이지 API 중복 요청 

### ISSUE THREAD

**Issue by birdieHyun** [Upbrella/Upbrella_front#289]
## 📌 Feature

<img width="1496" alt="스크린샷 2023-12-21 오후 12 34 43" src="https://github.com/UPbrella/UPbrella_front/assets/115435784/251cda22-46fe-4c16-b528-80d7df3c41c0">

우산 관리 페이지 관리 페이지에서 지점별 필터로 요청을 보낼 때,
지점 필터 API + 전체 우산 조회 API 
총 두 번 API 요청이 일어나는것 같은데 확인해주실 수 있으실까요? 

## 📜 To Do

- [ ]

**Comment by ShinChanU** [comment]
이제 확인했네요 !

제 기억에는, 테이블 용 페이지네이션(부분) 요청 1개와, 엑셀 다운로드용 전체 요청 1개를 작성했던 것으로 기억합니다 ..!

근데 `전체`가 아닌 지점 필터여도 `전체` 우산이 다운로드가 되는 것 같네요. 이건 한번 확인해보겠습니다 !

@birdieHyun

**Comment by ShinChanU** [comment]
수정 후에 배포했습니다  !
동현님 말씀처럼 지점 필터 시에도 전체 요청을 했더라구요 ! 그 부분 수정했습니다 !
확인 후 이슈 닫아주시면 감사하겠습니다 !

@birdieHyun

**Comment by birdieHyun** [comment]
감사합니다! 
그런데 확인해보니 이런 경우도 있는 것 같아서요 

<img width="242" alt="스크린샷 2023-12-26 오후 2 16 06" src="https://github.com/UPbrella/UPbrella_front/assets/115435784/9dbe8e46-81a5-4c5e-bf8a-9a1dc884b78c">

협업지점 id에 해당하는 우산들을 조회할 때, 기본 요청인 page=0&size=10 요청 -> 우산 통계를 조회 -> 우산 통계에 맞게 사이즈 조정 후 재요청 

이런 플로우로 진행되는 것 같은데 확인해주실 수 있으실까요? 

@ShinChanU

**Comment by ShinChanU** [comment]
네네 맞습니다!
다운로드해서 엑셀을 내려받을 때, 전체 우산 개수로 요청해야해서 그런 흐름으로 만들어 뒀습니다. 

@birdieHyun

**Comment by birdieHyun** [comment]
넵 감사합니다!
